# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  Archives: archives
  Videos: https://www.youtube.com/channel/UCX_yFupNOERhc1qt0e8JFqA/featured?view_as=subscriber
  About: about


# Set default keywords (Use a comma to separate)
keywords: ""

# Put your favicon.ico into `hexo-site/themes/hipaper/source/` directory.
favicon: css/images/favicon.ico


# Put your avatar.jpg into `hexo-site/themes/hipaper/source/` directory.
# url is target link (E.g. `url: https://hexo.io/logo.svg` or `url: css/images/mylogo.jpg`)
avatar: 
  enable: false
  width: 124
  height: 124
  bottom: 10
  url: https://hexo.io/logo.svg


# AboutPage background, support multiple images.
about_big_image: 


# Homepage thumbnail
random_thumb: true


# Content
fancybox: true


# Sidebar
sidebar: right
widgets:
- search
- social
- recent_posts
- category
- tag
- tagcloud
- archive

# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  Twitter: https://twitter.com/TSgt_Green
  Github: https://github.com/bgreengo
  LinkedIn: https://www.linkedin.com/in/blakegreen2/



# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: d6ymCKsAyokCVGvk3DQJ # enter swiftype install key here



# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: default


# widget behavior
archive_type: 'monthly'
show_count: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:


# Miscellaneous
google_analytics: UA-123266487-1
twitter:

